import { Router } from "express";
import jwt from "jsonwebtoken";

// =============================================================
//  AUTH SCAFFOLD — DO NOT EDIT THIS FILE.
//  It exists only so you can obtain a real token to test with.
//  In a production app, login checks a hashed password in the
//  database. Here we use a tiny hard-coded demo user list.
// =============================================================

const router = Router();

const DEMO_USERS = [
  { id: 1, email: "ada@threadbase.dev", password: "password", role: "user" },
  { id: 2, email: "linus@threadbase.dev", password: "password", role: "admin" },
];

// POST /auth/login  ->  { accessToken, user }
router.post("/login", (req, res) => {
  const { email, password } = req.body ?? {};
  const user = DEMO_USERS.find(
    (u) => u.email === email && u.password === password
  );

  if (!user) {
    return res.status(401).json({ error: "Invalid email or password" });
  }

  const accessToken = jwt.sign(
    { userId: user.id, role: user.role }, // the payload verifyToken will decode
    process.env.JWT_SECRET,
    { expiresIn: "15m" }
  );

  res.json({
    accessToken,
    user: { id: user.id, email: user.email, role: user.role },
  });
});

// Stubs so the client's refresh/logout calls do not 404.
router.post("/refresh", (req, res) =>
  res.status(501).json({ error: "Not implemented in this scaffold" })
);
router.post("/logout", (req, res) => res.status(204).end());

export default router;
